# Generated by Django 5.0.6 on 2024-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
